package closure

import (
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"testing"
)

// The canonical digest is what a compiled Go member contributes: equal
// across comment-only and gofmt-only edits, moved by any token change
// and by any retained comment — a directive, a cgo preamble, the
// generated-file marker — and absent for text that does not scan
// (REQ-closure-canonical-member).
//
//gofresh:pure
func TestCanonicalDigestFoldsSyntaxAndRetainedComments(t *testing.T) {
	base := "package p\n\n// Doc comment.\nfunc F(a int) int {\n\t// inner\n\treturn a + 1\n}\n"
	digest, ok := canonicalDigest([]byte(base))
	if !ok {
		t.Fatal("base did not parse")
	}
	same := map[string]string{
		"comment removed":     "package p\n\nfunc F(a int) int {\n\treturn a + 1\n}\n",
		"comment reworded":    "package p\n\n// Another doc.\nfunc F(a int) int {\n\t/* block */ return a + 1\n}\n",
		"layout changed":      "package p\n\n\n\nfunc F(a  int)   int {\n\n\n\treturn a+1\n\n}\n",
		"nolint kept alike":   "package p\n\nfunc F(a int) int {\n\treturn a + 1 // nolint\n}\n",
		"line directive":      "package p\n\n//line other.go:10\nfunc F(a int) int {\n\treturn a + 1\n}\n",
		"explicit semicolons": "package p\n\n// Doc comment.\nfunc F(a int) int {\n\treturn a + 1;\n};\n",
	}
	for name, variant := range same {
		got, ok := canonicalDigest([]byte(variant))
		if !ok || got != digest {
			t.Errorf("%s: digest %s (parsed %v), want the base's %s", name, got, ok, digest)
		}
	}
	moved := map[string]string{
		"token changed":         "package p\n\nfunc F(a int) int {\n\treturn a + 2\n}\n",
		"semicolon moved":       "package p\n\nfunc F(a int) int { return a + 1 }\n",
		"go directive":          "package p\n\n//go:noinline\nfunc F(a int) int {\n\treturn a + 1\n}\n",
		"gofresh directive":     "package p\n\n//gofresh:pure\nfunc F(a int) int {\n\treturn a + 1\n}\n",
		"tool directive":        "package p\n\n//nolint:all\nfunc F(a int) int {\n\treturn a + 1\n}\n",
		"generated marker":      "// Code generated by gen. DO NOT EDIT.\n\npackage p\n\nfunc F(a int) int {\n\treturn a + 1\n}\n",
		"export directive":      "package p\n\n//export F\nfunc F(a int) int {\n\treturn a + 1\n}\n",
		"block directive":       "package p\n\n/*go:linkname F other.F*/\nfunc F(a int) int {\n\treturn a + 1\n}\n",
		"legacy build tag":      "// +build linux\n\npackage p\n\nfunc F(a int) int {\n\treturn a + 1\n}\n",
		"trailing-space marker": "// Code generated by gen. DO NOT EDIT. \n\npackage p\n\nfunc F(a int) int {\n\treturn a + 1\n}\n",
	}
	for name, variant := range moved {
		got, ok := canonicalDigest([]byte(variant))
		if !ok || got == digest {
			t.Errorf("%s: digest %s (parsed %v) equals the base's — a retained class or a token was dropped", name, got, ok)
		}
	}
	// Retained comments fold by their text, so a change inside one moves
	// the digest exactly as a token change does.
	a, _ := canonicalDigest([]byte("package p\n\n//go:noinline\nfunc F() {}\n"))
	b, _ := canonicalDigest([]byte("package p\n\n//go:nosplit\nfunc F() {}\n"))
	if a == b {
		t.Fatal("two directives folded alike")
	}
	// The cgo preamble is C code: any change to it moves the digest,
	// whether it documents a lone import or a grouped spec.
	preamble := "package p\n\n// #include <stdio.h>\nimport \"C\"\n\nfunc F() { C.puts(nil) }\n"
	edited := "package p\n\n// #include <stdlib.h>\nimport \"C\"\n\nfunc F() { C.puts(nil) }\n"
	grouped := "package p\n\nimport (\n\t// #include <stdio.h>\n\t\"C\"\n)\n\nfunc F() { C.puts(nil) }\n"
	groupedEdited := "package p\n\nimport (\n\t// #include <stdlib.h>\n\t\"C\"\n)\n\nfunc F() { C.puts(nil) }\n"
	for _, pair := range [][2]string{{preamble, edited}, {grouped, groupedEdited}} {
		x, okx := canonicalDigest([]byte(pair[0]))
		y, oky := canonicalDigest([]byte(pair[1]))
		if !okx || !oky || x == y {
			t.Fatalf("cgo preamble edit did not move the digest (%s / %s)", x, y)
		}
	}
	// A retained comment folds with its attachment: a blank line between
	// a directive and its declaration detaches the doc the parser (and
	// gofresh's directive readers) see, with an identical token stream.
	attached, _ := canonicalDigest([]byte("package p\n\n//gofresh:pure\nfunc F() int { return 1 }\n"))
	detached, _ := canonicalDigest([]byte("package p\n\n//gofresh:pure\n\nfunc F() int { return 1 }\n"))
	if attached == detached {
		t.Fatal("a detached directive folded like an attached one")
	}
	// The rule is the parser's, per group: a directive first in a doc
	// group stays live when the group is contiguous and dies when a
	// blank line splits the group; a group closed by a block comment on
	// the declaration's own line is no doc group at all.
	contiguous, _ := canonicalDigest([]byte("package p\n\n//gofresh:pure\n// docs\nfunc F() {}\n"))
	split, _ := canonicalDigest([]byte("package p\n\n//gofresh:pure\n\n// docs\nfunc F() {}\n"))
	if contiguous == split {
		t.Fatal("a directive split from its doc group folded like a contiguous one")
	}
	plain, _ := canonicalDigest([]byte("package p\n\n//gofresh:pure\nfunc F() {}\n"))
	closedOnLine, _ := canonicalDigest([]byte("package p\n\n//gofresh:pure\n/* x */ func F() {}\n"))
	if plain == closedOnLine {
		t.Fatal("a group closed by a block comment on the declaration's line folded like a lead group")
	}
	// A legacy constraint is read by its field, in any spelling: two
	// no-space lines naming different tags are two forms.
	tightLinux, _ := canonicalDigest([]byte("//go:build linux\n//+build linux\n\npackage p\n"))
	tightDarwin, _ := canonicalDigest([]byte("//go:build linux\n//+build darwin\n\npackage p\n"))
	if tightLinux == tightDarwin {
		t.Fatal("a no-space +build line was dropped")
	}
	// A comment before a "C" string outside an import group is not a
	// preamble: the group tracking closes with its parenthesis.
	before, _ := canonicalDigest([]byte("package p\n\nimport (\n\t\"fmt\"\n)\n\nvar x = // alpha\n\"C\"\n\nvar _ = fmt.Sprint\n"))
	afterEdit, _ := canonicalDigest([]byte("package p\n\nimport (\n\t\"fmt\"\n)\n\nvar x = // beta\n\"C\"\n\nvar _ = fmt.Sprint\n"))
	if before != afterEdit {
		t.Fatal("a comment before a plain \"C\" literal after an import group was retained as a preamble")
	}
	// The stream keeps its semicolons: two programs differing only by
	// a line break that inserts one are two forms.
	call, _ := canonicalDigest([]byte("package p\n\nfunc F() { x := y(z); _ = x }\n"))
	statement, _ := canonicalDigest([]byte("package p\n\nfunc F() { x := y\n\t(z); _ = x }\n"))
	if call == statement {
		t.Fatal("a call and a statement break folded alike — the automatic semicolon was dropped")
	}
	// Text the scanner refuses (an unterminated literal) has no
	// canonical form: the member folds its bytes.
	unscannable := []byte("package p\n\nvar s = \"unterminated\n")
	if _, ok := canonicalDigest(unscannable); ok {
		t.Fatal("unscannable text produced a canonical digest")
	}
	h := &Hasher{}
	if got := h.canonicalFileDigest(t.TempDir(), "bytes-digest", unscannable); got != "bytes-digest" {
		t.Fatalf("unscannable member folded %q, want its byte digest", got)
	}
}

// For every syntactically valid member, inserting non-retained comments
// anywhere between lines and re-indenting the whitespace leaves the
// canonical digest unchanged, while changing one token moves it —
// over a seeded enumeration of members and edits.
func TestCanonicalDigestIsInvariantUnderCommentAndLayoutEdits(t *testing.T) {
	rng := rand.New(rand.NewSource(129))
	for round := 0; round < 200; round++ {
		n := 1 + rng.Intn(4)
		body := "package p\n\n"
		for i := 0; i < n; i++ {
			name := fmt.Sprintf("f%d%c", rng.Intn(1000), 'a'+rune(i))
			body += "func " + name + "(x int) int {\n\tif x > " + fmt.Sprint(rng.Intn(9)) + " {\n\t\treturn x\n\t}\n\treturn -x\n}\n\n"
		}
		base, ok := canonicalDigest([]byte(body))
		if !ok {
			t.Fatalf("round %d: generated member did not parse:\n%s", round, body)
		}
		commented := ""
		for _, line := range splitLines(body) {
			if rng.Intn(2) == 0 {
				text := make([]byte, rng.Intn(20))
				for k := range text {
					text[k] = byte(' ' + rng.Intn('~'-' '+1))
				}
				commented += "// " + string(text) + "\n"
			}
			if rng.Intn(2) == 0 {
				line = "    " + line
			}
			commented += line + "\n"
		}
		if got, ok := canonicalDigest([]byte(commented)); !ok || got != base {
			t.Fatalf("round %d: comment/layout edit moved the digest:\n%s", round, commented)
		}
		if renamed, ok := canonicalDigest([]byte(body[:len(body)-8] + "-x - 1\n}\n\n")); !ok || renamed == base {
			t.Fatalf("round %d: token edit did not move the digest", round)
		}
	}
}

func splitLines(s string) []string {
	var lines []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			lines = append(lines, s[start:i])
			start = i + 1
		}
	}
	if start < len(s) {
		lines = append(lines, s[start:])
	}
	return lines
}

// A comment-only edit to a mutable-local member leaves every subject's
// maximal closure standing, and its canonical digest serves from the
// memo on a byte-equal pass while a byte-moved member derives once
// (REQ-closure-canonical-member, REQ-closure-effect-scan-memo).
func TestCommentOnlyEditKeepsTheMaximalClosure(t *testing.T) {
	if testing.Short() {
		t.Skip("builds a module fixture and runs the closure fold over it")
	}
	t.Setenv("XDG_CACHE_HOME", t.TempDir())
	dir := fileMemoModule(t)
	var derived []string
	analysisTestHooks.canonicalParse = func(d string) { derived = append(derived, filepath.Base(d)) }
	defer func() { analysisTestHooks.canonicalParse = nil }()
	before, _, _ := foldOnce(t, dir, true)
	if len(derived) == 0 {
		t.Fatal("the cold pass derived no canonical digest")
	}
	derived = nil
	if _, _, _ = foldOnce(t, dir, true); len(derived) != 0 {
		t.Fatalf("a byte-equal warm pass derived %d canonical digest(s), want the memo to serve", len(derived))
	}
	helper := filepath.Join(dir, "helper.go")
	// Comments and layout only — no line break that would insert a
	// semicolon (a different syntax tree is a different form).
	if err := os.WriteFile(helper, []byte("package fm\n\n\n// helper is documented now.\nfunc   helper() int { /* one */ return 1 } // trailing\n\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	derived = nil
	after, _, _ := foldOnce(t, dir, true)
	if len(derived) == 0 {
		t.Fatal("a byte-moved member derived no canonical digest")
	}
	for _, subject := range fileMemoSubjects {
		if before[subject].Hash != after[subject].Hash {
			t.Fatalf("%s: a comment-only edit moved the maximal closure %s → %s", subject.Symbol, before[subject].Hash, after[subject].Hash)
		}
	}
	if err := os.WriteFile(helper, []byte("package fm\n\nfunc helper() int { return 2 }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	changed, _, _ := foldOnce(t, dir, true)
	for _, subject := range fileMemoSubjects {
		if before[subject].Hash == changed[subject].Hash {
			t.Fatalf("%s: a token edit left the maximal closure at %s", subject.Symbol, changed[subject].Hash)
		}
	}
}

// A member reaching the binary as data contributes its bytes whatever
// its name: an embedded text member, and a compiled Go member a
// go:embed directive names too — its comment edit changes the program
// (the embedded string) with an unchanged canonical form, so its form
// must never be its contribution (REQ-closure-canonical-member,
// REQ-closure-floor).
func TestEmbeddedMembersContributeBytes(t *testing.T) {
	if testing.Short() {
		t.Skip("builds a module fixture and runs the closure fold over it")
	}
	t.Setenv("XDG_CACHE_HOME", t.TempDir())
	dir := t.TempDir()
	write := func(name, content string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("go.mod", "module example.com/em\n\ngo 1.26\n")
	write("self.go", "package em\n\nimport _ \"embed\"\n\n//go:embed self.go\nvar Self string\n\n//go:embed data.txt\nvar Data string\n\n// a comment\nfunc Len() int { return len(Self) + len(Data) }\n")
	write("data.txt", "// data\n")
	write("self_test.go", "package em\n\nimport \"testing\"\n\nfunc TestLen(t *testing.T) { _ = Len() }\n")
	subjects := []Subject{{Package: "example.com/em", Symbol: "Len"}}
	fold := func() string {
		t.Helper()
		h, err := NewAt(dir)
		if err != nil {
			t.Fatal(err)
		}
		got, err := h.ComputeMaximalBatch(subjects)
		if err != nil {
			t.Fatal(err)
		}
		return got[subjects[0]].Hash
	}
	base := fold()
	write("self.go", "package em\n\nimport _ \"embed\"\n\n//go:embed self.go\nvar Self string\n\n//go:embed data.txt\nvar Data string\n\n// a longer comment now\nfunc Len() int { return len(Self) + len(Data) }\n")
	if fold() == base {
		t.Fatal("a comment edit to a self-embedded compiled member left the closure standing — its bytes are the program")
	}
	write("self.go", "package em\n\nimport _ \"embed\"\n\n//go:embed self.go\nvar Self string\n\n//go:embed data.txt\nvar Data string\n\n// a comment\nfunc Len() int { return len(Self) + len(Data) }\n")
	if fold() != base {
		t.Fatal("restoring the member did not restore the closure")
	}
	write("data.txt", "// data edited\n")
	if fold() == base {
		t.Fatal("a comment-looking edit to an embedded text member left the closure standing")
	}
}
